### ISSUE TITLE
Getting error when I try to apply example-secret.yaml

### ISSUE THREAD

**Issue by s-u-b-h-a-k-a-r** [werne2j/arogcd-vault-plugin-demo#1]
kubectl apply -f example-secret.yaml

Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|ple\u003e"},"kind":"|..., bigger context ...|:"v1","data":{"sample-secret":"\u003csample\u003e"},"kind":"Secret","metadata":{"annotations":{"avp_|...

**Comment by werne2j** [comment]
Make sure the argocd-vault-plugin is appropriately installed and selected for the ArgoCD application that is pointing to this repo

**Comment by werne2j** [comment]
@s-u-b-h-a-k-a-r this issue should be fixed since we now support kv2
